paths:
  data_root: data
  prepared_dir: prepared
  outputs_dir: outputs
  logs_dir: logs
  huggingface_cache: "${USERPROFILE}\\.cache\\huggingface"
  models_mount: "..\\outputs"
  run_metadata_file: logs/latest.txt

preprocess:
  dataset_name: tatsu-lab/alpaca
  sample_size: 32
  filter_langs:
    - en
  test_size: 0.2
  cutoff_len: 1024
  seed: 215
  save_splits: true
  max_workers: 2
  pack_sequences: false

train:
  base_model: Qwen/Qwen2.5-0.5B
  cutoff_len: 512
  batch_size: 1
  gradient_accumulation: 1
  epochs: 1
  learning_rate: 0.00002
  min_learning_rate: 0.000005
  weight_decay: 0.01
  warmup_ratio: 0.03
  lr_scheduler: cosine
  lora_r: 4
  lora_alpha: 16
  lora_dropout: 0.05
  lora_target_modules:
    - q_proj
    - k_proj
    - v_proj
    - o_proj
    - gate_proj
    - up_proj
    - down_proj
  gradient_checkpointing: true
  bf16: false
  fp16: false
  logging_steps: 1
  eval_steps: 5
  max_steps: 10
  resume_from: null

export:
  include_adapter_weights: true
  resume_from: null

eval:
  cutoff_len: 512
  max_new_tokens: 64
  temperature: 0.7
  top_p: 0.9
  prompts:
    - instruction: "Summarize the Alpaca dataset in one sentence."
      language: en
      max_sentences: 1
  resume_from: null

serve:
  host: 0.0.0.0
  port: 8080
  max_model_len: 512
  served_model_name: Qwen2.5-0.5B-SFT-DEBUG
  served_model_relpath: none
  resume_from: null

logging:
  console_level: INFO
  file_level: DEBUG
  tqdm_refresh_rate: 0.5
  debug_pipeline: true

awq:
  enabled: true
  gpu_enabled: false
  method: awq
  scheme: W4A16_ASYM
  num_calibration_samples: 32
  calib_text_file: prepared/awq_calibration.txt
  extra_args: []
  use_smoothquant: true
  smoothquant_strength: 0.8
  max_seq_length: 1024
  output_suffix: awq
  ignore:
    - lm_head
